// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe8roKuw7B0mpb7QPBs9u-b55m95LGk9A',
    appId: '1:470798589767:web:016d93b1c6c95dd5f0b662',
    messagingSenderId: '470798589767',
    projectId: 'notes-authentication-firebase',
    authDomain: 'notes-authentication-firebase.firebaseapp.com',
    storageBucket: 'notes-authentication-firebase.firebasestorage.app',
    measurementId: 'G-QQLW73KY2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzcqemHsAgKE-MUWRoSE1Mre5uD0HEwfI',
    appId: '1:470798589767:android:4c13011792be2a9af0b662',
    messagingSenderId: '470798589767',
    projectId: 'notes-authentication-firebase',
    storageBucket: 'notes-authentication-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTCH5GJ_gnPYa6TOz1d6svbZs_h0FXug',
    appId: '1:470798589767:ios:e2417ef258d4f970f0b662',
    messagingSenderId: '470798589767',
    projectId: 'notes-authentication-firebase',
    storageBucket: 'notes-authentication-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterNoteApplication',
  );
}
